[tool.poetry]
name = "nodice2"
version = "2.0.0-alpha"
description = "Dicebot on qq"
authors = ["Jigsaw <j1g5aw@foxmail.com>"]
license = "AGPLv3"

[tool.poetry.dependencies]
python = "^3.7.3"
nonebot2 = "^2.0.0-alpha.11"
nonebot-plugin-manager = "^0.1.0.post1"
hjson = "^3.0.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
